### ISSUE TITLE
Linux Mint Import Error 

### ISSUE THREAD

**Issue by oliviaguest** [conda-forge/caffe-feedstock#22] opened 2016-11-22 17:33 UTC
I ran the commands for installing a caffe environment but it doesn't work at all, it seems. I'm on Linux Mint and used the following:

```
olivia@Love11 ~/Downloads $ conda create -n CAFFE -c conda-forge caffe
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/olivia/anaconda2/envs/CAFFE:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2016.9.26  |                0         162 KB  conda-forge
    gettext-0.19.7             |                1         5.6 MB  conda-forge
    gflags-2.1.2               |                0          85 KB  conda-forge
    glog-0.3.4                 |                0         570 KB  conda-forge
    icu-56.1                   |                4        21.9 MB  conda-forge
    jpeg-9b                    |                0         918 KB  conda-forge
    libffi-3.2.1               |                2          47 KB  conda-forge
    libiconv-1.14              |                3         2.0 MB  conda-forge
    lmdb-0.9.18                |                0         499 KB  conda-forge
    ncurses-5.9                |                9         954 KB  conda-forge
    pcre-8.38                  |                1         631 KB  conda-forge
    pixman-0.34.0              |                0         3.6 MB  conda-forge
    snappy-1.1.3               |                2         103 KB  conda-forge
    sqlite-3.13.0              |                1         4.9 MB  conda-forge
    tk-8.5.19                  |                0         1.9 MB  conda-forge
    xz-5.2.2                   |                0         853 KB  conda-forge
    yaml-0.1.6                 |                0         300 KB  conda-forge
    zlib-1.2.8                 |                3          87 KB  conda-forge
    glib-2.48.0                |                4         4.7 MB  conda-forge
    hdf5-1.8.17                |                7         3.9 MB  conda-forge
    jasper-1.900.1             |                3         271 KB  conda-forge
    leveldb-1.18               |                0         308 KB  conda-forge
    libpng-1.6.26              |                0         297 KB  conda-forge
    libtiff-4.0.6              |                7         507 KB  conda-forge
    libxml2-2.9.4              |                3         4.9 MB  conda-forge
    openblas-0.2.19            |                0        14.1 MB  conda-forge
    openssl-1.0.2h             |                2         3.4 MB  conda-forge
    readline-6.2               |                0         713 KB  conda-forge
    blas-1.1                   |         openblas           1 KB  conda-forge
    freetype-2.6.3             |                1         2.8 MB  conda-forge
    python-2.7.12              |                1        15.5 MB  conda-forge
    backports.shutil_get_terminal_size-1.0.0|           py27_0           5 KB  conda-forge
    boost-1.62.0               |           py27_0        17.3 MB  conda-forge
    certifi-2016.9.26          |           py27_0         217 KB  conda-forge
    decorator-4.0.10           |           py27_0          12 KB  conda-forge
    enum34-1.1.6               |           py27_1          54 KB  conda-forge
    fontconfig-2.11.1          |                3         874 KB  conda-forge
    functools32-3.2.3.2        |           py27_1          16 KB  conda-forge
    ipython_genutils-0.1.0     |           py27_0          33 KB  conda-forge
    numpy-1.11.2               |py27_blas_openblas_202         7.1 MB  conda-forge
    pillow-3.4.2               |           py27_0         926 KB  conda-forge
    ptyprocess-0.5.1           |           py27_0          19 KB  conda-forge
    pyparsing-2.1.10           |           py27_0          91 KB  conda-forge
    python-gflags-2.0          |           py27_1          52 KB  conda-forge
    python-leveldb-0.193       |           py27_0         1.0 MB  conda-forge
    pytz-2016.7                |           py27_0         161 KB  conda-forge
    pyyaml-3.11                |           py27_0         339 KB  conda-forge
    simplegeneric-0.8.1        |           py27_0           6 KB  conda-forge
    sip-4.18                   |           py27_0         263 KB  conda-forge
    six-1.10.0                 |           py27_1          18 KB  conda-forge
    wcwidth-0.1.7              |           py27_0          22 KB  conda-forge
    cairo-1.12.18              |                8         1.1 MB  conda-forge
    cycler-0.10.0              |           py27_0          13 KB  conda-forge
    h5py-2.6.0                 |      np111py27_7         2.7 MB  conda-forge
    networkx-1.11              |           py27_0         1.5 MB  conda-forge
    opencv-2.4.12              |      np111py27_2         7.8 MB  conda-forge
    pathlib2-2.1.0             |           py27_0          26 KB  conda-forge
    pexpect-4.2.1              |           py27_0          65 KB  conda-forge
    python-dateutil-2.6.0      |           py27_0         232 KB  conda-forge
    scipy-0.17.1               |np111py27_blas_openblas_205        31.4 MB  conda-forge
    setuptools-28.8.0          |           py27_0         356 KB  conda-forge
    traitlets-4.3.1            |           py27_0         121 KB  conda-forge
    harfbuzz-1.0.6             |                0         3.0 MB  conda-forge
    pandas-0.19.1              |      np111py27_0        16.7 MB  conda-forge
    pickleshare-0.7.3          |           py27_0           8 KB  conda-forge
    protobuf-3.0.0             |           py27_0         6.6 MB  conda-forge
    pygments-2.1.3             |           py27_1         1.2 MB  conda-forge
    wheel-0.29.0               |           py27_0          81 KB  conda-forge
    pango-1.40.1               |                0         912 KB  conda-forge
    pip-9.0.1                  |           py27_0         1.6 MB  conda-forge
    prompt_toolkit-1.0.9       |           py27_0         313 KB  conda-forge
    ipython-5.1.0              |           py27_1         980 KB  conda-forge
    qt-4.8.7                   |                3        31.3 MB  conda-forge
    pyqt-4.11.4                |           py27_1         3.5 MB  conda-forge
    matplotlib-1.5.3           |      np111py27_2         6.6 MB  conda-forge
    scikit-image-0.12.3        |      np111py27_0        27.3 MB  conda-forge
    caffe-1.0.0rc3             |py27_blas_openblas_203         2.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       272.6 MB

The following NEW packages will be INSTALLED:

    backports.shutil_get_terminal_size: 1.0.0-py27_0                       conda-forge
    blas:                               1.1-openblas                       conda-forge
    boost:                              1.62.0-py27_0                      conda-forge
    ca-certificates:                    2016.9.26-0                        conda-forge
    caffe:                              1.0.0rc3-py27_blas_openblas_203    conda-forge [blas_openblas]
    cairo:                              1.12.18-8                          conda-forge
    certifi:                            2016.9.26-py27_0                   conda-forge
    cycler:                             0.10.0-py27_0                      conda-forge
    decorator:                          4.0.10-py27_0                      conda-forge
    enum34:                             1.1.6-py27_1                       conda-forge
    fontconfig:                         2.11.1-3                           conda-forge
    freetype:                           2.6.3-1                            conda-forge
    functools32:                        3.2.3.2-py27_1                     conda-forge
    gettext:                            0.19.7-1                           conda-forge
    gflags:                             2.1.2-0                            conda-forge
    glib:                               2.48.0-4                           conda-forge
    glog:                               0.3.4-0                            conda-forge
    h5py:                               2.6.0-np111py27_7                  conda-forge
    harfbuzz:                           1.0.6-0                            conda-forge
    hdf5:                               1.8.17-7                           conda-forge
    icu:                                56.1-4                             conda-forge
    ipython:                            5.1.0-py27_1                       conda-forge
    ipython_genutils:                   0.1.0-py27_0                       conda-forge
    jasper:                             1.900.1-3                          conda-forge
    jpeg:                               9b-0                               conda-forge
    leveldb:                            1.18-0                             conda-forge
    libffi:                             3.2.1-2                            conda-forge
    libgfortran:                        3.0.0-1                                       
    libiconv:                           1.14-3                             conda-forge
    libpng:                             1.6.26-0                           conda-forge
    libtiff:                            4.0.6-7                            conda-forge
    libxml2:                            2.9.4-3                            conda-forge
    lmdb:                               0.9.18-0                           conda-forge
    matplotlib:                         1.5.3-np111py27_2                  conda-forge
    ncurses:                            5.9-9                              conda-forge
    networkx:                           1.11-py27_0                        conda-forge
    numpy:                              1.11.2-py27_blas_openblas_202      conda-forge [blas_openblas]
    openblas:                           0.2.19-0                           conda-forge
    opencv:                             2.4.12-np111py27_2                 conda-forge
    openssl:                            1.0.2h-2                           conda-forge
    pandas:                             0.19.1-np111py27_0                 conda-forge
    pango:                              1.40.1-0                           conda-forge
    pathlib2:                           2.1.0-py27_0                       conda-forge
    pcre:                               8.38-1                             conda-forge
    pexpect:                            4.2.1-py27_0                       conda-forge
    pickleshare:                        0.7.3-py27_0                       conda-forge
    pillow:                             3.4.2-py27_0                       conda-forge
    pip:                                9.0.1-py27_0                       conda-forge
    pixman:                             0.34.0-0                           conda-forge
    prompt_toolkit:                     1.0.9-py27_0                       conda-forge
    protobuf:                           3.0.0-py27_0                       conda-forge
    ptyprocess:                         0.5.1-py27_0                       conda-forge
    pygments:                           2.1.3-py27_1                       conda-forge
    pyparsing:                          2.1.10-py27_0                      conda-forge
    pyqt:                               4.11.4-py27_1                      conda-forge
    python:                             2.7.12-1                           conda-forge
    python-dateutil:                    2.6.0-py27_0                       conda-forge
    python-gflags:                      2.0-py27_1                         conda-forge
    python-leveldb:                     0.193-py27_0                       conda-forge
    pytz:                               2016.7-py27_0                      conda-forge
    pyyaml:                             3.11-py27_0                        conda-forge
    qt:                                 4.8.7-3                            conda-forge
    readline:                           6.2-0                              conda-forge
    scikit-image:                       0.12.3-np111py27_0                 conda-forge
    scipy:                              0.17.1-np111py27_blas_openblas_205 conda-forge [blas_openblas]
    setuptools:                         28.8.0-py27_0                      conda-forge
    simplegeneric:                      0.8.1-py27_0                       conda-forge
    sip:                                4.18-py27_0                        conda-forge
    six:                                1.10.0-py27_1                      conda-forge
    snappy:                             1.1.3-2                            conda-forge
    sqlite:                             3.13.0-1                           conda-forge
    tk:                                 8.5.19-0                           conda-forge
    traitlets:                          4.3.1-py27_0                       conda-forge
    wcwidth:                            0.1.7-py27_0                       conda-forge
    wheel:                              0.29.0-py27_0                      conda-forge
    xz:                                 5.2.2-0                            conda-forge
    yaml:                               0.1.6-0                            conda-forge
    zlib:                               1.2.8-3                            conda-forge

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
ca-certificate 100% |##################################| Time: 0:00:00 358.06 kB/s
gettext-0.19.7 100% |##################################| Time: 0:00:02   2.51 MB/s
gflags-2.1.2-0 100% |##################################| Time: 0:00:00 285.02 kB/s
glog-0.3.4-0.t 100% |##################################| Time: 0:00:00 593.82 kB/s
icu-56.1-4.tar 100% |##################################| Time: 0:00:03   6.87 MB/s
jpeg-9b-0.tar. 100% |##################################| Time: 0:00:01 696.45 kB/s
libffi-3.2.1-2 100% |##################################| Time: 0:00:00 196.26 kB/s
libiconv-1.14- 100% |##################################| Time: 0:00:01   1.18 MB/s
lmdb-0.9.18-0. 100% |##################################| Time: 0:00:00 603.14 kB/s
ncurses-5.9-9. 100% |##################################| Time: 0:00:01 701.39 kB/s
pcre-8.38-1.ta 100% |##################################| Time: 0:00:00 711.47 kB/s
pixman-0.34.0- 100% |##################################| Time: 0:00:02   1.74 MB/s
snappy-1.1.3-2 100% |##################################| Time: 0:00:00 276.29 kB/s
sqlite-3.13.0- 100% |##################################| Time: 0:00:02   2.43 MB/s
tk-8.5.19-0.ta 100% |##################################| Time: 0:00:01   1.44 MB/s
xz-5.2.2-0.tar 100% |##################################| Time: 0:00:01 712.01 kB/s
yaml-0.1.6-0.t 100% |##################################| Time: 0:00:00 359.84 kB/s
zlib-1.2.8-3.t 100% |##################################| Time: 0:00:00 271.07 kB/s
glib-2.48.0-4. 100% |##################################| Time: 0:00:02   2.17 MB/s
hdf5-1.8.17-7. 100% |##################################| Time: 0:00:02   2.05 MB/s
jasper-1.900.1 100% |##################################| Time: 0:00:00 447.18 kB/s
leveldb-1.18-0 100% |##################################| Time: 0:00:00 518.07 kB/s
libpng-1.6.26- 100% |##################################| Time: 0:00:00 440.25 kB/s
libtiff-4.0.6- 100% |##################################| Time: 0:00:00 672.81 kB/s
libxml2-2.9.4- 100% |##################################| Time: 0:00:02   2.33 MB/s
openblas-0.2.1 100% |##################################| Time: 0:00:03   3.75 MB/s
openssl-1.0.2h 100% |##################################| Time: 0:00:02   1.66 MB/s
readline-6.2-0 100% |##################################| Time: 0:00:01 709.19 kB/s
blas-1.1-openb 100% |##################################| Time: 0:00:00 504.22 kB/s
freetype-2.6.3 100% |##################################| Time: 0:00:01   1.57 MB/s
python-2.7.12- 100% |##################################| Time: 0:00:03   4.88 MB/s
backports.shut 100% |##################################| Time: 0:00:00   1.60 MB/s
boost-1.62.0-p 100% |##################################| Time: 0:00:03   4.66 MB/s
certifi-2016.9 100% |##################################| Time: 0:00:00 413.73 kB/s
decorator-4.0. 100% |##################################| Time: 0:00:00   3.76 MB/s
enum34-1.1.6-p 100% |##################################| Time: 0:00:00 190.04 kB/s
fontconfig-2.1 100% |##################################| Time: 0:00:01 773.11 kB/s
functools32-3. 100% |##################################| Time: 0:00:00 206.00 kB/s
ipython_genuti 100% |##################################| Time: 0:00:00  44.35 kB/s
numpy-1.11.2-p 100% |##################################| Time: 0:00:02   3.44 MB/s
pillow-3.4.2-p 100% |##################################| Time: 0:00:01 701.32 kB/s
ptyprocess-0.5 100% |##################################| Time: 0:00:00  22.10 kB/s
pyparsing-2.1. 100% |##################################| Time: 0:00:00 294.90 kB/s
python-gflags- 100% |##################################| Time: 0:00:00 224.53 kB/s
python-leveldb 100% |##################################| Time: 0:00:00   1.09 MB/s
pytz-2016.7-py 100% |##################################| Time: 0:00:00 292.58 kB/s
pyyaml-3.11-py 100% |##################################| Time: 0:00:00 453.43 kB/s
simplegeneric- 100% |##################################| Time: 0:00:00   2.07 MB/s
sip-4.18-py27_ 100% |##################################| Time: 0:00:00 467.58 kB/s
six-1.10.0-py2 100% |##################################| Time: 0:00:00 236.37 kB/s
wcwidth-0.1.7- 100% |##################################| Time: 0:00:00 278.42 kB/s
cairo-1.12.18- 100% |##################################| Time: 0:00:01 776.29 kB/s
cycler-0.10.0- 100% |##################################| Time: 0:00:00 156.43 kB/s
h5py-2.6.0-np1 100% |##################################| Time: 0:00:01   1.82 MB/s
networkx-1.11- 100% |##################################| Time: 0:00:01 983.70 kB/s
opencv-2.4.12- 100% |##################################| Time: 0:00:02   3.51 MB/s
pathlib2-2.1.0 100% |##################################| Time: 0:00:00 339.48 kB/s
pexpect-4.2.1- 100% |##################################| Time: 0:00:00 291.71 kB/s
python-dateuti 100% |##################################| Time: 0:00:00 407.36 kB/s
scipy-0.17.1-n 100% |##################################| Time: 0:00:04   7.98 MB/s
setuptools-28. 100% |##################################| Time: 0:00:00 431.23 kB/s
traitlets-4.3. 100% |##################################| Time: 0:00:00 278.86 kB/s
harfbuzz-1.0.6 100% |##################################| Time: 0:00:01   1.75 MB/s
pandas-0.19.1- 100% |##################################| Time: 0:00:03   5.09 MB/s
pickleshare-0. 100% |##################################| Time: 0:00:00   2.67 MB/s
protobuf-3.0.0 100% |##################################| Time: 0:00:01   3.60 MB/s
pygments-2.1.3 100% |##################################| Time: 0:00:01 778.44 kB/s
wheel-0.29.0-p 100% |##################################| Time: 0:00:00 270.63 kB/s
pango-1.40.1-0 100% |##################################| Time: 0:00:01 717.01 kB/s
pip-9.0.1-py27 100% |##################################| Time: 0:00:01 889.25 kB/s
prompt_toolkit 100% |##################################| Time: 0:00:00 406.49 kB/s
ipython-5.1.0- 100% |##################################| Time: 0:00:01 823.29 kB/s
qt-4.8.7-3.tar 100% |##################################| Time: 0:00:03   8.40 MB/s
pyqt-4.11.4-py 100% |##################################| Time: 0:00:02   1.73 MB/s
matplotlib-1.5 100% |##################################| Time: 0:00:02   3.12 MB/s
scikit-image-0 100% |##################################| Time: 0:00:03   8.34 MB/s
caffe-1.0.0rc3 100% |##################################| Time: 0:00:01   1.45 MB/s
Extracting packages ...
[      COMPLETE      ]|#####################################################| 100%
Linking packages ...
[      COMPLETE      ]|#####################################################| 100%
#
# To activate this environment, use:
# > source activate CAFFE
#
# To deactivate this environment, use:
# > source deactivate CAFFE
#

olivia@Love11 ~/Downloads $ source activate CAFFE

(CAFFE) olivia@Love11 ~/GitHub/caffe-video_triplet/python $ python -c 'import caffe; print(caffe.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe
```

**Comment by jakirkham** [comment] 2016-11-23 07:18
Thanks for the bug report. Unable to reproduce this on the CentOS 6 docker image currently. Could you please provide some more info about your system like what version of Linux Mint and glibc version?

**Comment by 183amir** [comment] 2016-11-23 08:45
You are probably importing your local version of caffe because of your
current folder. Try changing your current folder and importing caffe again.

**Comment by oliviaguest** [comment] 2016-11-23 11:37
I am probably being dim but don't I need to be in that folder to run those python scripts for the neural network?

**Comment by jakirkham** [comment] 2016-11-23 16:28
Good catch @183amir .

So we install the executable Python scripts in the conda environment. This way you can run them wherever you need to.

That being said, if you still need those importable scripts, maybe just rename the directory to `caffe_python` or something else so as not to conflict. Then you should be able to import them.

**Comment by oliviaguest** [comment] 2016-11-24 10:15
Nope!

```
olivia@Love11 ~/GitHub/caffe-video_triplet/caffe_python $  source activate CAFFE
(CAFFE) olivia@Love11 ~/GitHub/caffe-video_triplet/caffe_python $ python -c 'import caffe; print(caffe.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe
```

**Comment by oliviaguest** [comment] 2016-11-24 13:28
Aha! Ignore above - was definitely being way way too under-caffeinated. Solved because of your advice! Thanks!

**Comment by 183amir** [comment] 2016-11-25 23:00
@oliviaguest I am closing this since looks like your problem is solved and it's not related to this feedstock anyway.

**Closed by 183amir** 2016-11-25 23:00 UTC

**Comment by jakirkham** [comment] 2016-11-27 00:58
Yeah, it looks like the `from ._caffe import ...` is getting you in trouble as that is a shared object that is only in the built package of `caffe`. You might be able to do something really hacky and add a symlink to where it is in `site-packages`. I don't really recommend it, but Caffe's Python packaging is suboptimal. So it may be an acceptable short-term solution.

In any event, thanks for raising this. It reminded me to bump issue ( https://github.com/BVLC/caffe/issues/4170 ) again.

**Comment by oliviaguest** [comment] 2016-11-27 09:47
I didn't have a line with that though. For what it's worth all I have was "import caffe" nothing with an underscore. Ideally I'd like to be able install caffe without a virtual environment, but have not managed it so far. I would like to use my Titan X too.

**Comment by jakirkham** [comment] 2016-11-27 15:16
It appears in your traceback. 😕

**Comment by oliviaguest** [comment] 2016-11-27 16:58
@jakirkham The traceback is a result of running the following as you can see from above too: ```python -c 'import caffe; print(caffe.__version__)'```
Nothing in that line contains caffe with an underscore. Am I missing something?

**Comment by jakirkham** [comment] 2016-11-27 17:34
What are the contents of your current directory?

**Comment by oliviaguest** [comment] 2016-11-27 17:37
The problem is fixed because I was within the caffe directory. So now even I start the virtual environment it works.
